# NOTE: This compose file assumes the service is being created as a stack,
#  'dcd-itpeople'. If you need to change the stack name, you'll want to change
#  the label services/functions/deploy/labels/com.docker.lb.network as well.
version: "3.3"
services:
  functions:
    image: uitsssl/itpeople-functions:develop
    networks:
      - backend
    working_dir: /home/site/wwwroot
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        com.docker.lb.hosts: "itpeople-api.apps-test.iu.edu"
        com.docker.lb.network: "dcd-itpeople_backend"
        com.docker.lb.port: 80
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: "36a9cb35-1b64-4224-9426-d4da8b21a4c1"
      FUNCTIONS_WORKER_RUNTIME: "dotnet"
      AzureWebJobsDisableHomepage: "true"
      CorsHosts: "https://itpeople.apps-test.iu.edu"
      OAuthClientId: "uxo-skunkworks"
      OAuthTokenUrl: "https://apps-test.iu.edu/uaa-stg/oauth/token"
      OAuthRedirectUrl: "https://itpeople.apps-test.iu.edu/signin"
      UseFakeData: "false"
    secrets:
      - source: itpeople-functions-OAuthClientSecret
        target: OAuthClientSecret
      - source: itpeople-functions-DbConnectionString
        target: DbConnectionString
      - source: itpeople-functions-JwtSecret
        target: JwtSecret
networks:
  backend:
    driver: overlay
secrets:
  itpeople-functions-OAuthClientSecret:
    external: true
  itpeople-functions-DbConnectionString:
    external: true
  itpeople-functions-JwtSecret:
    external: true
