swagger: '2.0'
info:
  version: v1
  title: IT People API
  description: IT People is the canonical source of information about the organization of IT units and people at Indiana University
  contact:
    name: UITS DCD
    email: dcdreq@iu.edu
paths:
  /auth:
    get:
      tags:
        - Authentication
      summary: Get OAuth JWT
      description: Exchanges a UAA OAuth code for an application-scoped JWT. The JWT is required to make authenticated requests to this API.
      operationId: auth
      consumes: []
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/JwtResponse'
          examples:
            application/json:
              access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOiIxNTE1NTQ0NjQzIiwidXNlcl9pZCI6MSwidXNlcl9uYW1lIjoiam9obmRvZSIsInVzZXJfcm9sZSI6ImFkbWluIn0.akuT7-xDFxrev-T9Dv0Wdumx1HK5L2hQAOU51igIjUE
  /supportRelationships:
    get:
      tags:
        - Support Relationships
      summary: List all unit-department support relationships.
      operationId: supportRelationshipsGetAll
      consumes: []
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SupportRelationship'
          examples:
            application/json:
              id: 1
              unitId: 1
              departmentId: 1
              department:
                id: 1
                name: PA-PARKS
                description: Parks and Recreation Department
              unit:
                id: 1
                name: City of Pawnee
                description: 'City of Pawnee, Indiana'
                url: ''
                parentId: null
    post:
      tags:
        - Support Relationships
      summary: Create a unit-department support relationship
      operationId: supportRelationshipsCreate
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: foo
          required: true
          schema:
            $ref: '#/definitions/SupportRelationshipRequest'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/SupportRelationship'
          examples:
            application/json:
              id: 1
              unitId: 1
              departmentId: 1
              department:
                id: 1
                name: PA-PARKS
                description: Parks and Recreation Department
              unit:
                id: 1
                name: City of Pawnee
                description: 'City of Pawnee, Indiana'
                url: ''
                parentId: null
  '/supportRelationships/{relationshipId}':
    get:
      tags:
        - Support Relationships
      summary: Find a unit-department support relationships by ID
      operationId: supportRelationshipsGetId
      consumes: []
      produces:
        - application/json
      parameters:
        - name: relationshipId
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/SupportRelationship'
          examples:
            application/json:
              - id: 1
                unitId: 1
                departmentId: 1
                department:
                  id: 1
                  name: PA-PARKS
                  description: Parks and Recreation Department
                unit:
                  id: 1
                  name: City of Pawnee
                  description: 'City of Pawnee, Indiana'
                  url: ''
                  parentId: null
definitions:
  JwtResponse:
    type: object
    properties:
      access_token:
        description: 'The OAuth JSON Web Token (JWT) that represents the logged-in user. The JWT must be passed in an HTTP Authentication header in the form: ''Bearer &lt;JWT&gt;'''
        type: string
        readOnly: true
  SupportRelationship:
    description: This relationship describes which IT Unit provides IT-related support for a given department.
    type: object
    properties:
      id:
        format: int32
        description: The unique ID of this unit record.
        type: integer
      unitId:
        format: int32
        description: The unique ID of the unit in this relationship
        type: integer
      departmentId:
        format: int32
        description: The unique ID of the department in this relationship
        type: integer
      department:
        $ref: '#/definitions/Department'
        description: The department in this relationship.
      unit:
        $ref: '#/definitions/Unit'
        description: The unit in this relationship.
  Department:
    description: An academic or administrative department
    type: object
    properties:
      id:
        format: int32
        description: The unique ID of this department record.
        type: integer
      name:
        description: The name of this department.
        type: string
      description:
        description: A description or longer name of this department.
        type: string
  Unit:
    description: An IT unit
    type: object
    properties:
      id:
        format: int32
        description: The unique ID of this unit record.
        type: integer
      name:
        description: The name of this unit.
        type: string
      description:
        description: A description of this unit.
        type: string
      url:
        description: A URL for the website of this unit.
        type: string
      parentId:
        format: int32
        description: The unique ID of the parent unit of this unit.
        type: integer
  SupportRelationshipRequest:
    type: object
    properties:
      unitId:
        format: int32
        description: The unique ID of the unit in this relationship
        type: integer
        readOnly: true
      departmentId:
        format: int32
        description: The unique ID of the department in this relationship
        type: integer
        readOnly: true
    example:
      unitId: 1
      departmentId: 1
tags: []
